version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: clave1
    volumes:
      - $HOME/datos-postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: adrianbg09@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9091:80"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "9092:80"
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./miweb:/var/www/html

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./miweb:/var/www/html
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=admin
      - DB_USER=admin
      - DB_PASSWORD=clave1
    depends_on:
      - postgres
